// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: FileServer.proto

package server

import (
	"context"

	"XcxcPan/Server/XcXcPanFileServer/XcXcPanFileServer"
	"XcxcPan/Server/XcXcPanFileServer/internal/logic"
	"XcxcPan/Server/XcXcPanFileServer/internal/svc"
)

type XcXcPanFileServiceServer struct {
	svcCtx *svc.ServiceContext
	XcXcPanFileServer.UnimplementedXcXcPanFileServiceServer
}

func NewXcXcPanFileServiceServer(svcCtx *svc.ServiceContext) *XcXcPanFileServiceServer {
	return &XcXcPanFileServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *XcXcPanFileServiceServer) SayHello(ctx context.Context, in *XcXcPanFileServer.SayHelloRequest) (*XcXcPanFileServer.SayHelloResponse, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}

func (s *XcXcPanFileServiceServer) UploadChunk(ctx context.Context, in *XcXcPanFileServer.UploadChunkRequest) (*XcXcPanFileServer.UploadChunkResponse, error) {
	l := logic.NewUploadChunkLogic(ctx, s.svcCtx)
	return l.UploadChunk(in)
}

func (s *XcXcPanFileServiceServer) DelChunk(ctx context.Context, in *XcXcPanFileServer.DelChunkRequest) (*XcXcPanFileServer.DelChunkResponse, error) {
	l := logic.NewDelChunkLogic(ctx, s.svcCtx)
	return l.DelChunk(in)
}
